/*
 * Copyright 2018 Evgeny Naumenko <jk.vc@mail.ru>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.github.jk1.license.task

import org.gradle.api.DefaultTask

/**
 * No longer does anything: the data required by {@link CheckLicenseTask} is now always generated by
 * {@link ReportTask}. Kept so that builds referring to the task keep working.
 *
 * @deprecated For removal. Depend on {@code checkLicense} or {@code generateLicenseReport} instead.
 */
@Deprecated
class CheckLicensePreparationTask extends DefaultTask {

    CheckLicensePreparationTask() {
        group = "CheckingPreparation"
        description = "Prepare for checkLicense (deprecated, does nothing)"
    }
}
