---
name: release-manual
run-name: "🚀 Manual Release ${{ inputs.tag_name }} (via ${{ github.ref_name }})"

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: "branch, tag or SHA to publish"
        type: string
        default: ""
      validate_only:
        description: "Validate but do not upload the plugin"
        type: boolean
        default: true

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name || github.ref }}
  cancel-in-progress: true

jobs:
  release-manual:
    uses: ./.github/workflows/publish.yml
    with:
      tag_name: ${{ inputs.tag_name }}
      validate_only: ${{ inputs.validate_only }}
    secrets:
      publish_key: ${{ vars.JK1_GRADLE_PUBLISH_KEY }}
      publish_secret: ${{ secrets.JK1_GRADLE_PUBLISH_SECRET }}
      signing_key_id: ${{ vars.JK1_GRADLE_SIGNING_KEY_ID || '' }}
      signing_password: ${{ secrets.JK1_GRADLE_SIGNING_PASSWORD || '' }}
      signing_key: ${{ secrets.JK1_GRADLE_SIGNING_KEY || '' }}
