name: Run tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref_name }}
  cancel-in-progress: true

env:
  CI: "true"

jobs:
  build:
    strategy:
      matrix:
        test-java-version: [8, 11, 17, 21, 25]
      fail-fast: false

    name: build (test with Java ${{ matrix.test-java-version }})
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set up JDKs
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
          java-version: | # Last version in list is the default that Gradle will run with
            ${{ matrix.test-java-version }}
            17
          distribution: temurin
          check-latest: true

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@50e97c2cd7a37755bbfafc9c5b7cafaece252f6e # v6.1.0

      - name: Build with Gradle
        run: ./gradlew -PtestToolchainJdkVersion=${{ matrix.test-java-version }} build publishToMavenLocal

      - name: Problems Report
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        if: always()
        with:
          name: problems-report-${{ matrix.test-java-version }}
          path: build/reports/problems/problems-report.html
          if-no-files-found: ignore

      - name: Unit tests results
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        if: always()
        with:
          name: unit-tests-results-${{ matrix.test-java-version }}
          path: build/reports/tests/test

      - name: Sanity check samples
        working-directory: samples
        env:
          # Gradle 8.x does not have support for Java 25 on Kotlin due to a Kotlin 2.2 bug https://github.com/gradle/gradle/issues/35111
          # Can run for Java 25 on Kotlin once we upgrade samples to Gradle v9 which would drop Java 8/11 testing.
          SAMPLES: ${{ matrix.test-java-version != '25' && 'groovy kotlin' || 'groovy' }}
        run: |
          export JAVA_HOME=$JAVA_HOME_${{ matrix.test-java-version }}_X64
          for sample in $SAMPLES; do
            echo "Checking $sample sample" && cd "$sample" && ./gradlew generateLicenseReport && cd -
          done